spring:
  datasource:
    url: jdbc:mysql://prod-db:3306/mis_prod?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8
    username: mis_prod
    password: mis_prod_123
  data:
    redis:
      host: prod-redis
      port: 6379
      password: mis_prod_redis_123
      database: 0

logging:
  level:
    root: warn
    com.mis: info
    org.springframework: error
    org.mybatis: warn
    com.alibaba.druid: error 