spring:
  datasource:
    url: jdbc:mysql://uat-db:3306/mis_uat?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false&serverTimezone=GMT%2B8
    username: mis_uat
    password: mis_uat_123
  data:
    redis:
      host: uat-redis
      port: 6379
      password: mis_uat_redis_123
      database: 0

logging:
  level:
    root: info
    com.mis: info
    org.springframework: warn
    org.mybatis: info
    com.alibaba.druid: warn 