server:
  port: 8084

spring:
  application:
    name: mis-ai
  ai:
    openai:
      api-key: ${OPENAI_API_KEY}
      model: gpt-3.5-turbo
    ollama:
      model: llama2

logging:
  level:
    root: INFO
    com.mis.ai: DEBUG 