spring:
  datasource:
    url: jdbc:mysql://prod-db:3306/mis_prod?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8
    username: mis_prod
    password: mis_prod_123
  data:
    redis:
      host: prod-redis
      port: 6379
      password: mis_prod_redis_123
      database: 0
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://auth.mis.com
          jwk-set-uri: https://auth.mis.com/oauth2/jwks

jwt:
  secret: prod-secret-key-here
  expiration: 86400  # 24 hours in seconds

logging:
  level:
    org.springframework.security: warn
    com.mis.auth: warn 