spring:
  datasource:
    url: jdbc:mysql://uat-db:3306/mis_uat?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false&serverTimezone=GMT%2B8
    username: mis_uat
    password: mis_uat_123
  data:
    redis:
      host: uat-redis
      port: 6379
      password: mis_uat_redis_123
      database: 0
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://uat-auth.mis.com
          jwk-set-uri: http://uat-auth.mis.com/oauth2/jwks

jwt:
  secret: uat-secret-key-here
  expiration: 86400  # 24 hours in seconds

logging:
  level:
    org.springframework.security: info
    com.mis.auth: info 